# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'GetMusicLibrary' do
  pod 'RealmSwift'
end

target 'GetMusicLibraryTests' do
  pod 'RealmSwift'
end

target 'GetMusicLibraryUITests' do
  pod 'RealmSwift'
end

