# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleForAudioKit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AudioKit', '~> 3.5'
  # Pods for SampleForAudioKit

end
